### ISSUE TITLE
Maximum Recursion depth hit while running worker

### ISSUE THREAD

**Issue by iamkhush** [nvie/rq#315]
So, when a job takes a lot of time to execute, other jobs in queue can have their hashes timeout, which is currently 500sec by default.

Now in my case, we have a large number of jobs coming in, but have relatively lesser number of workers. When they do timeout, we get this error, Maximum recursion depth exceeded while calling a Python object. I believe that it is recursively looking for jobs in queue which still have fresh hashes present. 

```
20:06:40 *** Listening on default...
Traceback (most recent call last):
File "/home/ubuntu/lcfenv/bin/rqworker", line 8, in 
load_entry_point('rq==0.3.13', 'console_scripts', 'rqworker')()
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/scripts/rqworker.py", line 90, in main
w.work(burst=args.burst)
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/worker.py", line 311, in work
result = self.dequeue_job_and_maintain_ttl(timeout)
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/worker.py", line 346, in dequeue_job_and_maintain_ttl
connection=self.connection)
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/queue.py", line 286, in dequeue_any
return cls.dequeue_any(queues, timeout, connection=connection)
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/queue.py", line 286, in dequeue_any
return cls.dequeue_any(queues, timeout, connection=connection)
File "/home/ubuntu/lcfenv/local/lib/python2.7/site-packages/rq/queue.py", line 286, in dequeue_any
return cls.dequeue_any(queues, timeout, connection=connection)
..........
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by selwin** [comment]
This is fixed in https://github.com/nvie/rq/pull/506
