### ISSUE TITLE
Since version 5.0 of rq my web2py app with redis didnt work anymore

### ISSUE THREAD

**Issue by corebyte** [nvie/rq#483]
Hi,

I have some web2py apps running and since i had a new server recently with pip install rq i discovered that i got a None exception from the job queuing it in redis.

I downgraded to 0.4.6 which version i also have on my older server, restarted apache2 and it worked again!

So there is something wrong.

If you need more debug info, feel free to ask!

**Comment by selwin** [comment]
Hi @corebyte , can you elaborate more on how the queueing process works in your app? It would also be good if you could provide a failing test case that we can take a look at.

**Comment by iamlittle** [comment]
I think I have the same issue. In 0.5.0, it appears that REDIS_HOST and REDIS_PORT are ignored in the config file. For example (the same configuration works in 0.4.6): 

rqconfig.py:
```python
REDIS_HOST= '172.17.0.215'
REDIS_PORT= 6379
QUEUE=["foo"]
```

`rqworker -c rqconfig` results in: 
```
Traceback (most recent call last):
  File "/usr/local/bin/rqworker", line 9, in <module>
    load_entry_point('rq==0.5.0', 'console_scripts', 'rqworker')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 162, in worker
    cleanup_ghosts(conn)
  File "/usr/local/lib/python2.7/dist-packages/rq/contrib/legacy.py", line 25, in cleanup_ghosts
    for worker in Worker.all(connection=conn):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 91, in all
    reported_working = connection.smembers(cls.redis_workers_keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1515, in smembers

    return self.execute_command('SMEMBERS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
**Notice it is trying to connect to the localhost.** 

This Dockerfile will reproduce the error:
```
FROM debian

RUN pip install rq==0.5.0
RUN echo "REDIS_HOST='172.17.0.215'\nREDIS_PORT=6379\nQUEUE=['foo']\n" > /rqconfig.py

ENTRYPOINT ["rqworker", "-c", "rqconfig"]
```

This Dockerfile will show the same thing works in 0.4.6
```
FROM debian

RUN pip install rq==0.4.6
RUN echo "REDIS_HOST='172.17.0.215'\nREDIS_PORT=6379\nQUEUE=['foo']\n" > /rqconfig.py

ENTRYPOINT ["rqworker", "-c", "rqconfig"]
```

**Comment by selwin** [comment]
Ah ok, so it seems like it's ignoring the connection params in the config file. Does it work if you pass in the connection parameters via command line?

**Comment by iamlittle** [comment]
The args have changed, so I'm not sure if I'm doing it correctly. `rqworker -H 172.17.0.215` works in 0.4.6, `rqworker -u 172.17.0.215` gives me:

```
Traceback (most recent call last):
  File "/usr/local/bin/rqworker", line 9, in <module>
    load_entry_point('rq==0.5.0', 'console_scripts', 'rqworker')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 162, in worker
    cleanup_ghosts(conn)
  File "/usr/local/lib/python2.7/dist-packages/rq/contrib/legacy.py", line 25, in cleanup_ghosts
    for worker in Worker.all(connection=conn):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 91, in all
    reported_working = connection.smembers(cls.redis_workers_keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1515, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to None:6379. Connection refused.
```

**Comment by selwin** [comment]
@iamlittle try using this: `rqworker -u redis://172.17.0.215:6379` and see if it works.

Alternatively, you could put `REDIS_URL = "redis://172.17.0.215:6379"` in your config file. See if both works.

**Comment by selwin** [comment]
If both works, I'll update the docs accordingly.

**Comment by selwin** [comment]
This commit removes a whole host of arguments to the CLI scripts https://github.com/nvie/rq/pull/420/files so the new CLI scripts only accepts URL based Redis configuration which is cleaner, but not backwards compatible.

**Comment by selwin** [comment]
@iamlittle I opened a PR for this. Could you please check https://github.com/nvie/rq/pull/491 to see if it solves your problem? You should now be able to specify `REDIS_HOST = 'localhost'` in config file like in prior versions.

**Comment by nvie** [comment]
Let me know if it works for you, and I'll publish 0.5.1 with this patch.

**Comment by iamlittle** [comment]
I just verified that #491 does allow for host specification. Thanks @selwin!

**Comment by selwin** [comment]
Closing this issue as fixed
