### ISSUE TITLE
NoSuchJobError on Heroku

### ISSUE THREAD

**Issue by khamaileon** [nvie/rq#570]
I keep having NoSuchJobError exceptions on Heroku. Here is my code and logs. Any ideas ?

startup.py

``` python
scheduler = django_rq.get_scheduler('default')

def reset():
    """Cancel all active jobs"""
    try:
        jobs = scheduler.get_jobs()
        for job in jobs:
            job.cancel()

    except NoSuchJobError:
        pass

def run():
    """Start task schedulers"""
    try:
        for feed in Feed.objects.all():
            scheduler.schedule(
                scheduled_time=datetime.now(),
                func=fetch_and_parse,
                args=[feed],
                interval=1,
                timeout=1800
            )
    except NoSuchJobError:
        reset()
        run()

def fetch_and_parse(feed):
    """Fetch and parse feed"""
    if feed.fetch():
        feed.parse()
    time.sleep(feed.interval-1)

def main():
    reset()
    run()
```

``` bash
rqworker.1 | Traceback (most recent call last): 09:36:43 rqworker.1 | File "/app/.heroku/python/lib/python3.4/site-packages/rq/queue.py", line 371, in dequeue_any Exception
rqworker.1 | job = cls.job_class.fetch(job_id, connection=connection)
rqworker.1 | File "/app/.heroku/python/lib/python3.4/site-packages/rq/job.py", line 294, in fetch
rqworker.1 | job.refresh()
rqworker.1 | File "/app/.heroku/python/lib/python3.4/site-packages/rq/job.py", line 396, in refresh
rqworker.1 | raise NoSuchJobError('No such job: {0}'.format(key))
rqworker.1 | rq.exceptions.NoSuchJobError: No such job: b'rq:job:587e4fab-a718-4e75-ae27-bb47c8e73c21'
```

**Comment by yaghmr** [comment]
Hi, have you follow this article https://devcenter.heroku.com/articles/python-rq ?

**Comment by khamaileon** [comment]
Yes I'm using Django RQ and RedisCloud instead of RedisToGo. Sometimes this can work for 2 days then I face a NoSuchJobError issue. Here is my settings and Procfile:

```python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'DB': 0
        }
    }
}

RQ_QUEUES = {
    'default': {
        'USE_REDIS_CACHE': 'default',
        'DEFAULT_TIMEOUT': 500
    }
}

RQ_SHOW_ADMIN_LINK = True
```

**Comment by yaghmr** [comment]
Look at this article http://racingtadpole.com/blog/redis-queue-with-django/ 
and try to use directly RQ without Django RQ. 

What RedisCloud  plan do you have?
