### ISSUE TITLE
utcparse failure

### ISSUE THREAD

**Issue by dustymugs** [nvie/rq#595]
Somehow, we perfectly got a valid datetime object where the milliseconds are not present.

```
Traceback (most recent call last):
  File "./rqworker.py", line 10, in <module>
    main()
  File "/ssd/granular-dev/alpine/data_warehouse/scripts/util/initialize.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "./rqworker.py", line 7, in main
    worker.main()
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/cli/cli.py", line 191, in worker
    w.work(burst=burst)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/worker.py", line 411, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/worker.py", line 446, in dequeue_job_and_maintain_ttl
    connection=self.connection)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/queue.py", line 368, in dequeue_any
    job = cls.job_class.fetch(job_id, connection=connection)
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/job.py", line 294, in fetch
    job.refresh()
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/job.py", line 409, in refresh
    self.created_at = to_date(as_text(obj.get('created_at')))
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/job.py", line 402, in to_date
    return utcparse(as_text(date_str))
  File "/ssd/granular-dev/local/lib/python2.7/site-packages/rq/utils.py", line 166, in utcparse
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%f+00:00')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-10-29T19:47:13+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'
```

**Comment by dustymugs** [comment]
Our quick patch. We'd rather use arrow but...

```
def utcparse(string):

    formats = [
        '%Y-%m-%dT%H:%M:%SZ',
        '%Y-%m-%dT%H:%M:%S.%f+00:00',
        '%Y-%m-%dT%H:%M:%S+00:00'
    ]
    for frmt in formats:
        try:
            return datetime.datetime.strptime(string, formats)
        except ValueError:
            continue
```

**Comment by selwin** [comment]
That's weird. Are you perhaps using a custom `Job` class or exception handler? Can you reproduce this error?

**Comment by dustymugs** [comment]
No custom ```Job``` class or exception handler. I can't manually reproduce this but in my production environments, it does appear every once in a while.

**Comment by selwin** [comment]
If you can produce a failing test case for this, would be great. I'm gonna close this issue for now. Please reopen if needed.

**Comment by Piusdan** [comment]
> No custom `Job` class or exception handler. I can't manually reproduce this but in my production environments, it does appear every once in a while.

Also getting a similar error @selwin were you able to fix on your end
