### ISSUE TITLE
getting a "need more than 1 value to unpack" 

### ISSUE THREAD

**Issue by Ideasrefined** [nvie/rq#606]
I am using pip version of rq. 

I have followed the example as given on "http://python-rq.org/" . 
When I enqueue a job it is enqueued successfully but when rqworker processes it the job is failed with the following dump.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 149, in import_attribute
    module_name, attribute = name.rsplit('.', 1)
ValueError: need more than 1 value to unpack

**Comment by selwin** [comment]
Can you give a snippet of code which does the enqueueing?

**Comment by Ideasrefined** [comment]
:Sorry: it was my mistake . I had an error in the queue name.
