### ISSUE TITLE
Not compatible with fakeredis

### ISSUE THREAD

**Issue by foxx** [nvie/rq#613]
RQ does not work with [FakeRedis][1], due to [this][2]

```
Traceback (most recent call last):
  File "hello.py", line 4, in <module>
    q = Queue(connection=r)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/rq/queue.py", line 58, in __init__
    self.connection = resolve_connection(connection)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/rq/connections.py", line 66, in resolve_connection
    return patch_connection(connection)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/rq/compat/connections.py", line 23, in patch_connection
    raise ValueError('A StrictRedis or Redis connection is required.')
ValueError: A StrictRedis or Redis connection is required.
```

Perhaps there should be some sort of flag that prevents type checking? Or perhaps in the spirit of duck typing, it should raise a warning rather than an exception?

[1]: https://github.com/jamesls/fakeredis
[2]: https://github.com/nvie/rq/blob/master/rq/compat/connections.py#L26

**Comment by foxx** [comment]
@nvie If I submit a PR that replaces this with a warning, would it be accepted?

**Comment by selwin** [comment]
I wrote a proposed fixed here: https://github.com/nvie/rq/issues/514#issuecomment-134038744

I thought I merged in the patch but I just checked the master branch again and it isn't in there. Feel free to submit a PR with that code snippet (or if you have a better solution, it's also ok).

**Comment by foxx** [comment]
Raised PR in #619
