### ISSUE TITLE
@job decorator doc example throwing error

### ISSUE THREAD

**Issue by nidhinpd** [nvie/rq#629]
So i tried the example in official doc
```
from rq.decorators import job
from redis import Redis
import time

redis_conn = Redis('localhost')

@job('low', connection=redis_conn,timeout=5)
def add(x,y):
	return x+y

job=add.delay(3,4)
time.sleep(2)
print job.result
```

and i ran rqworker low from the same directory.
But whenever i ran it i get the following error

```
11:02:54 *** Listening on low...
11:02:55 low: __main__.add(3, 4) (42d4f06a-bd08-43b0-afef-b7e45db07469)
11:02:55 AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 151, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 151, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
```

**Comment by selwin** [comment]
The error is usually caused by improper PATH variables in your python environment.

**Comment by lordcoste** [comment]
Hello, I've got the same error. I'm running all my code inside a Docker container. 

This is the error:
```
19:14:43 default: __main__.add(1, 2) (75ab9148-4aca-44bc-a41e-cffd368509ba)
19:14:43 AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/site-packages/rq/utils.py", line 151, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/site-packages/rq/utils.py", line 151, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'add'
19:14:43 Moving job to u'failed' queue
```

And this is the container I'm using:

https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python2.7/Dockerfile


Hope you can help me.

Thanks

**Comment by thieunguyen287** [comment]
Hello, I've got the same error. And finally found out when you run your script, module name is \_\_main__, and it has the 'add' attribute, then rq send to queue reference of \_\_main__.add(). But your worker module name is \_\_main__, too. And it has no 'add' attribute. 
Solution: you can put you job definition into another module and import it when you need to run.

jobs.py:

```
from rq.decorators import job
from redis import Redis

redis_conn = Redis('localhost')


@job('low', connection=redis_conn,timeout=5)
def add(x,y):
    return x+y
```


main.py:


```
import time
from jobs import add

job=add.delay(3,4)
time.sleep(2)
print job.result
```
