### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'

### ISSUE THREAD

**Issue by jeremy-rutman** [nvie/rq#645]
not clear what has changed but some time string is no longer returned in an expected format for me - clue for me anyone?

root@brain2:/home/pd_user/trendi# /usr/local/bin/rqworker pd_yonti

Traceback (most recent call last):
  File "/usr/local/bin/rqworker", line 11, in <module>
    sys.exit(worker())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 202, in worker
    w.work(burst=burst)
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 422, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 458, in dequeue_job_and_maintain_ttl
    connection=self.connection)
  File "/usr/local/lib/python2.7/dist-packages/rq/queue.py", line 385, in dequeue_any
    job = cls.job_class.fetch(job_id, connection=connection)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 294, in fetch
    job.refresh()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 409, in refresh
    self.created_at = to_date(as_text(obj.get('created_at')))
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 402, in to_date
    return utcparse(as_text(date_str))
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 167, in utcparse
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%f+00:00')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2016-01-18T10:13:52.391778Z' does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'

**Comment by proofit404** [comment]
Looks like some client start pushing jobs with wrong time specification to redis. I'm trying to parse created_at attribute of your job.

```python
>>> import datetime

>>> string = '2016-01-18T10:13:52.391778Z'

>>> datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/proofit404/.pyenv/versions/3.4.0/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/proofit404/.pyenv/versions/3.4.0/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '2016-01-18T10:13:52.391778Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
time data '2016-01-18T10:13:52.391778Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

>>> datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%f+00:00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/proofit404/.pyenv/versions/3.4.0/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/proofit404/.pyenv/versions/3.4.0/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '2016-01-18T10:13:52.391778Z' does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'
time data '2016-01-18T10:13:52.391778Z' does not match format '%Y-%m-%dT%H:%M:%S.%f+00:00'
```
As you can see it doesn't recognized by both rq datetime convention (pre 0.4 and current). Microseconds part is redundant here. You can try to figure out how many broken jobs you have in redis for now. Look at created_at hash value of all rq:job:*  keys.

**Comment by liorsbg** [comment]
Baaah Jeremy I did that on purpose. Right now only braini1 and extremeli
have a proper rq version

On Monday, 18 January 2016, jeremy rutman <notifications@github.com> wrote:

> not clear what has changed but time string is no longer returned in an
> expected format for me - clue for me anyone?
>
> root@brain2:/home/pd_user/trendi# /usr/local/bin/rqworker pd_yonti
>
> Traceback (most recent call last):
> File "/usr/local/bin/rqworker", line 11, in
> sys.exit(worker())
> File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in
> *call*
> return self.main(*args, **kwargs)
> File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in
> main
> rv = self.invoke(ctx)
> File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in
> invoke
> return ctx.invoke(self.callback, *
>
> *ctx.params) File "/usr/local/lib/python2.7/dist-packages/click/core.py",
> line 534, in invoke return callback(*args, **kwargs)
> File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 202, in
> worker
> w.work(burst=burst)
> File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 422, in
> work
> result = self.dequeue_job_and_maintain_ttl(timeout)
> File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 458, in
> dequeue_job_and_maintain_ttl
> connection=self.connection)
> File "/usr/local/lib/python2.7/dist-packages/rq/queue.py", line 385, in
> dequeue_any
> job = cls.job_class.fetch(job_id, connection=connection)
> File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 294, in fetch
> job.refresh()
> File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 409, in
> refresh
> self.created_at = to_date(as_text(obj.get('created_at')))
> File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 402, in
> to_date
> return utcparse(as_text(date_str))
> File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 167, in
> utcparse
> return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%f+00:00')
> File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
> (data_string, format))
> ValueError: time data '2016-01-18T10:13:52.391778Z' does not match format
> '%Y-%m-%dT%H:%M:%S.%f+00:00'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvie/rq/issues/645>.
>


-- 
Lior Sabag
*CTO*
Trendi Guru <http://trendiguru.com>
*054-561-6583*

**Comment by jeremy-rutman** [comment]
sorry my bad, we have a modified worker i didnt see

**Comment by proofit404** [comment]
I guess you need to close this issue so.
