### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by foxmask** [nvie/rq#671]
with RQ 0.5.6 / redis 2.10.5 I have a too many time this error : 

```python
Traceback (most recent call last):
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/lib/python3.4/site-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "[...]/lib/python3.4/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to localhost:6379. Connection timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "[...]/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "[...]/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "[...]/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "[...]/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "[...]/lib/python3.4/site-packages/django_th/management/commands/fire_publish_data.py", line 19, in handle
    publish_data.delay()
  File "[...]/lib/python3.4/site-packages/rq/decorators.py", line 41, in delay
    timeout=self.timeout, result_ttl=self.result_ttl, depends_on=depends_on)
  File "[...]/lib/python3.4/site-packages/django_rq/queues.py", line 42, in enqueue_call
    return self.original_enqueue_call(*args, **kwargs)
  File "[...]/lib/python3.4/site-packages/django_rq/queues.py", line 38, in original_enqueue_call
    return super(DjangoRQ, self).enqueue_call(*args, **kwargs)
  File "[...]/lib/python3.4/site-packages/rq/queue.py", line 216, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "[...]/lib/python3.4/site-packages/rq/queue.py", line 282, in enqueue_job
    pipe.execute()
  File "[...]/lib/python3.4/site-packages/redis/client.py", line 2641, in execute
    return execute(conn, stack, raise_on_error)
  File "[...]/lib/python3.4/site-packages/redis/client.py", line 2495, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "[...]/lib/python3.4/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to localhost:6379. Connection timed out.
```

I have this error when I just do one of them in a crontab : 

```python
python manage.py rqworker default --burst 
python manage.py rqworker high --burst
python manage.py rqworker low --burst 
```

**Comment by selwin** [comment]
It doesn'l look like this error is related to RQ. You may need to recheck your Redis config to see why the connection times out.
