### ISSUE TITLE
ResponseError on executing rq info

### ISSUE THREAD

**Issue by barun-saha** [nvie/rq#683]
Hi,

I recently started using RQ and django-rq. Things are working fine with django-rq with/without using a password with Redis. However, when a password is used, `rq info` throws the following exception:

```python
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/cli.py", line 128, in info
    refresh(interval, func, queues, raw, by_queue)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/helpers.py", line 182, in refresh
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/helpers.py", line 168, in show_both
    show_queues(queues, raw, by_queue)
  File "/usr/local/lib/python2.7/dist-packages/rq/cli/helpers.py", line 88, in show_queues
    qs = Queue.all()
  File "/usr/local/lib/python2.7/dist-packages/rq/queue.py", line 43, in all
    return [to_queue(rq_key) for rq_key in connection.smembers(cls.redis_queues_keys) if rq_key]
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1532, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: operation not permitted
```
No such exception is thrown when `rq info` is executed without Redis having any `requirepass` directive. Authentication via `redis-cli` seems to be working:
```shell
redis 127.0.0.1:6379> auth wrong_passwd
(error) ERR invalid password
redis 127.0.0.1:6379> auth correct_passwd
OK
redis 127.0.0.1:6379>
```

The Redis server version is 2.2.12 (00000000:0). I am running the worker process used by Django via `supervisor`. Inside Django, a job is submitted as:

```python
queue = django_rq.get_queue(settings.REDIS_QNAME)
job = queue.enqueue(a_task, data)
```

I read that RQ requires Redis > 2.6. Could that be any reason for the above error?

**Comment by selwin** [comment]
This seems like a configuration issue. You need to ensure that you've setup the username and password correctly.
