### ISSUE TITLE
ImportError cannot import module 'worker'

### ISSUE THREAD

**Issue by lawli3t** [nvie/rq#706]
I am currently trying to run tasks on a worker, which run fine when ran in async mode.

When trying to run rqworkers with the tasks I get an ImportError

```
 worker.parse_sip_file('/opt/sip_parsing/data/sip_packets.pcap127') from default
312814a1-cb48-418f-8115-c909abfb7c38
Failed 5 minutes ago

Traceback (most recent call last):
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/opt/sip_parsing/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'worker'
```

I read about setting the import path of rqworker which I tried setting via 

`rq worker --path /opt/sip_parsing/venv/lib/python3.4/site-packages/rq/`

but then i get an error about relative imports:

```
14:08:22 SystemError: Parent module '' not loaded, cannot perform relative import
Traceback (most recent call last):
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/opt/sip_parsing/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/worker.py", line 19, in <module>
    from .connections import get_current_connection
SystemError: Parent module '' not loaded, cannot perform relative import
Traceback (most recent call last):
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/opt/sip_parsing/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/sip_parsing/venv/lib/python3.4/site-packages/rq/worker.py", line 19, in <module>
    from .connections import get_current_connection
SystemError: Parent module '' not loaded, cannot perform relative import
```

Am I understanding something about the path wrong?

**Comment by selwin** [comment]
This is not a bug in RQ. It's likely that the environment variables for `rqworker` is not setup properly.
