### ISSUE TITLE
StrictRedis

### ISSUE THREAD

**Issue by stleon** [nvie/rq#755]
## Long story short

[Here](https://github.com/nvie/rq/blob/master/rq/connections.py#L7) we have some problem:

```
from redis import StrictRedis
```

Its seems, that uses old redis-py version (https://github.com/andymccurdy/redis-py/issues/533).

## Expected behaviour

No errors

## Actual behaviour

```
In [1]: from redis import StrictRedis
ImportError: cannot import name 'StrictRedis'
```

## Mine environment

- Python 3.5.1
- hiredis==0.2.0
- redis==2.10.5
- rq==0.6.0
- click==6.6

**Comment by proofit404** [comment]
Looks like you have some script named `redis` which appears first in your python path. I've looked at redis.py sources right now (master and release you're using). StrictRedis is present in the package.

**Comment by stleon** [comment]
I have already find a problem and close this issue

**Comment by ansh1221** [comment]
Hi @stleon what was the issue?

```
ERROR: Failure: ImportError (cannot import name ConnectionPool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/views/test_admin.py", line 10, in <module>
    import ckan.tests.helpers as helpers
  File "/usr/lib/ckan/default/src/ckan/ckan/tests/helpers.py", line 32, in <module>
    import rq
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/rq/__init__.py", line 6, in <module>
    from .connections import (Connection, get_current_connection, pop_connection,
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/rq/connections.py", line 7, in <module>
    from redis import StrictRedis
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/redis.py", line 15, in <module>
    from redis import ConnectionPool, Redis
ImportError: cannot import name ConnectionPool
```

I am facing this issue while testing, can you please suggest some help?
