### ISSUE TITLE
can't enqueue function from a package?

### ISSUE THREAD

**Issue by WeatherGod** [nvie/rq#760]
I am having the darnedest time getting rq to enqueue a function call from a package. It'll work just fine if I am enqueueing a function from a local file. For a normal package install (using setuptools.setup()), when I enqueue the function, I get the following error from the worker:
```
11:35:57 *** Listening on radarOps...
11:36:57 radarOps: rqsub._helpers.run_script('touch foobar waka', {}, '/home/broot', True, None, '/home/broot/None.o42', '/home/broot/None.e42') (3af5cb4d-df5d-4593-b25e-d28083385dce)
11:36:57 ZipImportError: bad local file header: /home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg
Traceback (most recent call last):
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ZipImportError: bad local file header: /home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg
Traceback (most recent call last):
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ZipImportError: bad local file header: /home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg
11:36:57 Moving job to u'failed' queue
```

Seeing that the error was about zip imports, I tried setting the `zip_safe=False` flag to setup() and installed again. I get a different error:
```
11:35:57 radarOps: rqsub._helpers.run_script('touch foobar waka', {}, '/home/broot', True, None, '/home/broot/None.o42', '/home/broot/None.e42') (4ac00a6b-d908-4c1f-a4b0-2a0da52272a4)
11:35:57 IOError: [Errno 21] Is a directory: '/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg'
Traceback (most recent call last):
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
IOError: [Errno 21] Is a directory: '/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg'
Traceback (most recent call last):
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
IOError: [Errno 21] Is a directory: '/home/broot/scratch/miniconda/envs/redis_test/lib/python2.7/site-packages/rqsub-1.0.0-py2.7.egg'
11:35:57 Moving job to u'failed' queue
```

I am really lost at this point. I am using the latest released versions of redis and redis-queue, and python 2.7.12.

**Comment by WeatherGod** [comment]
.... and right after posting this, I had an inspiration. I had initiated the worker earlier from the same directory that had the local version of the .py file before I had turned it into a package. It seems that the worker was carrying that state and causing conflicts somehow. Shutting off the worker and initiating a new worker worked perfectly!

**Comment by WeatherGod** [comment]
Actually, a bit more clarification. It seems that when the package in question is a zipped egg and that egg is updated since the worker has already ran once, it will fail with the ZipImport error on the next try. But, if I set zip_safe=False for the install, and the worker's initial job is with the egg package directory (not zipped egg), then subsequent changes to the package seem to be safe (at least, so far in my testing).
