### ISSUE TITLE
Jobs with `depends_on` result in `NoRedisConnectionException`

### ISSUE THREAD

**Issue by hendi** [nvie/rq#766]
Happens on `rq==0.7.0` with the following code:

```python
from rq import Queue
from redis import Redis
redis_conn = Redis(host="localhost", port=6379, db=0)
q = Queue(connection=redis_conn)
report_job = q.enqueue("generate_report")
q.enqueue("send_report", depends_on=report_job)
```

results in:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    q.enqueue("send_report", depends_on=report_job)
  File "<venv>/lib/python3.4/site-packages/rq/queue.py", line 273, in enqueue
    job_id=job_id, at_front=at_front, meta=meta)
  File "<venv>/lib/python3.4/site-packages/rq/queue.py", line 212, in enqueue_call
    if not self.job_class.exists(depends_on.id):
  File "<venv>/lib/python3.4/site-packages/rq/job.py", line 285, in exists
    conn = resolve_connection(connection)
  File "<venv>/lib/python3.4/site-packages/rq/connections.py", line 70, in resolve_connection
    raise NoRedisConnectionException('Could not resolve a Redis connection')
rq.connections.NoRedisConnectionException: Could not resolve a Redis connection
```

**Comment by hendi** [comment]
Using Connection contexts this works.

**Comment by WeatherGod** [comment]
This is the bug I noted towards the end of #762, which made me go to a different method that didn't error like this, but turns out doesn't respect job dependencies.

**Comment by WeatherGod** [comment]
btw, the fix is really simple as the `self.job_class.exists()` method does take a `connection` argument, and just about all of the other method calls in this function has that argument specified.

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/commit/6721463fdfa4553ae30e825dadf44b3c30e02895
