### ISSUE TITLE
Sporadic socket.error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by willgdjones** [nvie/rq#780]
HI there - I'm getting a sporadic error on my dashboard. Does anyone know what could be the issue?

I'm running a heroku server and in a seperate window:

`rq-dashboard --redis-url $REDIS_URL --port 4444`

Thanks for you help.

`Traceback (most recent call last):
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/bin/rq-dashboard", line 11, in <module>
    sys.exit(main())
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/rq_dashboard/cli.py", line 127, in main
    run(auto_envvar_prefix='RQ_DASHBOARD')
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/rq_dashboard/cli.py", line 123, in run
    app.run(host=bind, port=port)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/Users/fonz/Documents/Projects/heterogeneous/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe`

**Comment by willgdjones** [comment]
Turns out it was my amazon redis_url, putting down the refresh interval ( --interval ) to 5000 solved it.
